create table book(ref_id number(20),name varchar2(40), author varchar2(40),
is_issued varchar2(10),publication varchar2(40), edition varchar2(20), cost number
(20), lib_id number(10));
insert into book values(1,'The Da Vinci Code','Dan Brown','yes','Transworld','2nd',599,4);
insert into book values(2,'The Da Vinci Code','Dan Brown','yes','Transworld','2nd',599,4);
insert into book values(3,'The Da Vinci Code','Dan Brown','no','Transworld','2nd',599,4);
insert into book values(4,'The Da Vinci Code','Dan Brown','no','Transworld','2nd',599,4);
insert into book values(5,'The Da Vinci Code','Dan Brown','no','Transworld','2nd',599,4);
insert into book values(6,'The Book Thief','Zusak Marcus','no','Transworld','1st',799,2);
insert into book values(7,'The Book Thief','Zusak Marcus','no','Transworld','1st',799,2);
insert into book values(8,'The Book Thief','Zusak Marcus','no','Transworld','1st',799,2);
insert into book values(9,'The Kite Runner','Khaled Hosseini','yes','Bloomsbury','3rd',300,6);
insert into book values(10,'The Kite Runner','Khaled Hosseini','no','Bloomsbury','3rd',300,6);
insert into book values(11,'The Kite Runner','Khaled Hosseini','no','Bloomsbury','3rd',300,6);
insert into book values(12,'The Kite Runner','Khaled Hosseini','no','Bloomsbury','3rd',300,6);
insert into book values(13,'The Kite Runner','Khaled Hosseini','no','Bloomsbury','3rd',300,6);
insert into book values(14,'The Kite Runner','Khaled Hosseini','no','Bloomsbury','3rd',300,6);
insert into book values(15,'To Kill A Mockingbird','Harper Lee','yes','Random House','7th',250,1);
insert into book values(16,'To Kill A Mockingbird','Harper Lee','yes','Random House','7th',250,1);
insert into book values(17,'To Kill A Mockingbird','Harper Lee','yes','Random House','7th',250,1);
insert into book values(18,'To Kill A Mockingbird','Harper Lee','yes','Random House','7th',250,1);
insert into book values(19,'To Kill A Mockingbird','Harper Lee','yes','Random House','7th',250,1);
insert into book values(20,'To Kill A Mockingbird','Harper Lee','yes','Random House','7th',250,1);
insert into book values(21,'To Kill A Mockingbird','Harper Lee','yes','Random House','7th',250,1);
insert into book values(22,'To Kill A Mockingbird','Harper Lee','yes','Random House','7th',250,1);
insert into book values(23,'To Kill A Mockingbird','Harper Lee','yes','Random House','7th',250,1);
insert into book values(24,'To Kill A Mockingbird','Harper Lee','yes','Random House','7th',250,1);
insert into book values(25,'Life of Pi','Yann Martel','no','Canongate','2nd',400,7);
insert into book values(26,'Life of Pi','Yann Martel','no','Canongate','2nd',400,7);
insert into book values(27,'Life of Pi','Yann Martel','yes','Canongate','2nd',400,7);
insert into book values(28,'Life of Pi','Yann Martel','no','Canongate','2nd',400,7);
insert into book values(29,'Life of Pi','Yann Martel','no','Canongate','2nd',400,7);
insert into book values(30,'Life of Pi','Yann Martel','no','Canongate','2nd',400,7);
insert into book values(31,'Life of Pi','Yann Martel','no','Canongate','2nd',400,7);
insert into book values(32,'Harry Potter and the Deathly Hallows','J K Rowling','yes','Bloomsbury','1st',900,3);
insert into book values(33,'Harry Potter and the Deathly Hallows','J K Rowling','yes','Bloomsbury','1st',900,3);
insert into book values(34,'Harry Potter and the Deathly Hallows','J K Rowling','yes','Bloomsbury','1st',900,3);
insert into book values(35,'Harry Potter and the Deathly Hallows','J K Rowling','yes','Bloomsbury','1st',900,3);
insert into book values(36,'Harry Potter and the Deathly Hallows','J K Rowling','yes','Bloomsbury','1st',900,3);
insert into book values(37,'Harry Potter and the Deathly Hallows','J K Rowling','yes','Bloomsbury','1st',900,3);
insert into book values(38,'Harry Potter and the Deathly Hallows','J K Rowling','yes','Bloomsbury','1st',900,3);
insert into book values(39,'Harry Potter and the Deathly Hallows','J K Rowling','yes','Bloomsbury','1st',900,3);
insert into book values(40,'Harry Potter and the Deathly Hallows','J K Rowling','yes','Bloomsbury','1st',900,3);
insert into book values(41,'Hannibal','Thomas Harris','no','Random House','4th',850,2);
insert into book values(42,'Hannibal','Thomas Harris','no','Random House','4th',850,2);
insert into book values(43,'Hannibal','Thomas Harris','no','Random House','4th',850,2);
insert into book values(44,'Hannibal','Thomas Harris','no','Random House','4th',850,2);
insert into book values(45,'Hannibal','Thomas Harris','no','Random House','4th',850,2);
insert into book values(46,'The Lord of the Rings',' J R R Tolkein ','yes','Harper Collins','3rd',1250,10);
insert into book values(47,'The Lord of the Rings',' J R R Tolkein ','yes','Harper Collins','3rd',1250,10);
insert into book values(48,'The Lord of the Rings',' J R R Tolkein ','yes','Harper Collins','3rd',1250,10);
insert into book values(49,'The Lord of the Rings',' J R R Tolkein ','yes','Harper Collins','3rd',1250,10);
insert into book values(50,'The Lord of the Rings',' J R R Tolkein ','yes','Harper Collins','3rd',1250,10);
insert into book values(51,'Signals and Systems','Alan V Oppeinheim','yes','Tata McGrawHill','11th',750,8);
insert into book values(52,'Signals and Systems','Alan V Oppeinheim','yes','Tata McGrawHill','11th',750,8);
insert into book values(53,'Signals and Systems','Alan V Oppeinheim','yes','Tata McGrawHill','11th',750,8);
insert into book values(54,'Signals and Systems','Alan V Oppeinheim','no','Tata McGrawHill','11th',750,8);
insert into book values(55,'Signals and Systems','Alan V Oppeinheim','no','Tata McGrawHill','11th',750,8);
insert into book values(56,'Signals and Systems','Alan V Oppeinheim','no','Tata McGrawHill','11th',750,8);
insert into book values(57,'Engineering Mechanics','A K Tayal','no','Khanna Publishers','4th',250,9);
insert into book values(58,'Engineering Mechanics','A K Tayal','no','Khanna Publishers','4th',250,9);
insert into book values(59,'Engineering Mechanics','A K Tayal','no','Khanna Publishers','4th',250,9);
insert into book values(60,'Engineering Mechanics','A K Tayal','no','Khanna Publishers','4th',250,9);
insert into book values(61,'Engineering Mechanics','A K Tayal','no','Khanna Publishers','4th',250,9);
insert into book values(62,'Engineering Mechanics','A K Tayal','no','Khanna Publishers','4th',250,9);
insert into book values(63,'Dear Fatty','Dawn French','no','Random House','1st',300,2);
insert into book values(64,'Dear Fatty','Dawn French','no','Random House','1st',300,2);
insert into book values(65,'Dear Fatty','Dawn French','no','Random House','1st',300,2);
insert into book values(66,'Dear Fatty','Dawn French','no','Random House','1st',300,2);
insert into book values(67,'Dear Fatty','Dawn French','yes','Random House','1st',300,2);
insert into book values(68,'Dear Fatty','Dawn French','no','Random House','1st',300,2);
insert into book values(69,'The Namesake','Jhumpa Lahiri','yes','Penguin','5th',350,4);
insert into book values(70,'The Namesake','Jhumpa Lahiri','no','Penguin','5th',350,4);
insert into book values(71,'The Namesake','Jhumpa Lahiri','no','Penguin','5th',350,4);
insert into book values(72,'The Namesake','Jhumpa Lahiri','no','Penguin','5th',350,4);
insert into book values(73,'The Namesake','Jhumpa Lahiri','no','Penguin','5th',350,4);
insert into book values(74,'The Namesake','Jhumpa Lahiri','no','Penguin','5th',350,4);
insert into book values(75,'The Namesake','Jhumpa Lahiri','no','Penguin','5th',350,4);
insert into book values(76,'The Namesake','Jhumpa Lahiri','no','Penguin','5th',350,4);
insert into book values(77,'The Namesake','Jhumpa Lahiri','no','Penguin','5th',350,4);
insert into book values(78,'The Hitchhiker's Guide to the Galaxy','Stephen Hawking','yes','Prentice Hall','3rd',600,5);
insert into book values(79,'The Hitchhiker's Guide to the Galaxy','Stephen Hawking','yes','Prentice Hall','3rd',600,5);
insert into book values(80,'The Hitchhiker's Guide to the Galaxy','Stephen Hawking','yes','Prentice Hall','3rd',600,5);
insert into book values(81,'The Hitchhiker's Guide to the Galaxy','Stephen Hawking','no','Prentice Hall','3rd',600,5);
insert into book values(82,'The Hitchhiker's Guide to the Galaxy','Stephen Hawking','no','Prentice Hall','3rd',600,5);
insert into book values(83,'The Hitchhiker's Guide to the Galaxy','Stephen Hawking','no','Prentice Hall','3rd',600,5);
insert into book values(84,'The Hitchhiker's Guide to the Galaxy','Stephen Hawking','no','Prentice Hall','3rd',600,5);
insert into book values(85,'The Hitchhiker's Guide to the Galaxy','Stephen Hawking','no','Prentice Hall','3rd',600,5);
insert into book values(86,'The Hitchhiker's Guide to the Galaxy','Stephen Hawking','no','Prentice Hall','3rd',600,5);
insert into book values(87,'The Hitchhiker's Guide to the Galaxy','Stephen Hawking','no','Prentice Hall','3rd',600,5);
insert into book values(88,'The Adventures of Tom Sawyer','Mark Twain','no','Classic Library','1st',400,3);
insert into book values(89,'The Adventures of Tom Sawyer','Mark Twain','no','Classic Library','1st',400,3);
insert into book values(90,'The Adventures of Tom Sawyer','Mark Twain','no','Classic Library','1st',400,3);
insert into book values(91,'The Adventures of Tom Sawyer','Mark Twain','no','Classic Library','1st',400,3);
insert into book values(92,'The Adventures of Tom Sawyer','Mark Twain','no','Classic Library','1st',400,3);
insert into book values(93,'The Adventures of Tom Sawyer','Mark Twain','no','Classic Library','1st',400,3);
insert into book values(94,'The Adventures of Tom Sawyer','Mark Twain','no','Classic Library','1st',400,3);
insert into book values(95,'A Tale of Two Cities','Charles Dickens','yes','Penguin','4th',600,7);
insert into book values(96,'A Tale of Two Cities','Charles Dickens','yes','Penguin','4th',600,7);
insert into book values(97,'A Tale of Two Cities','Charles Dickens','yes','Penguin','4th',600,7);
insert into book values(98,'A Tale of Two Cities','Charles Dickens','no','Penguin','4th',600,7);
insert into book values(99,'A Tale of Two Cities','Charles Dickens','no','Penguin','4th',600,7);

